apiVersion: apps/v1
kind: Deployment
metadata:
  name: dstats
  namespace: dstats
  labels:
    app: dstats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dstats
  template:
    metadata:
      labels:
        app: dstats
    spec:     
      containers:
      - name: dstats
        image: arifcse21/dstats:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2743
          name: http
        env:
        - name: USE_AUTH
          value: "true"
        - name: AUTH_USERNAME
          value: "dstats-on-k8s"
        - name: AUTH_PASSWORD
          value: "dstats-on-k8s"
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: false
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket