apiVersion: v1
kind: Service
metadata:
  name: dstats-service
  namespace: dstats
  labels:
    app: dstats
spec:
  selector:
    app: dstats
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2743
  type: ClusterIP